<?php

namespace Wbi\ForumBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CommentsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Wbi\ForumBundle\Controller\CommentsController();
        return $instance;
    }
}
